### ISSUE TITLE
Bug: should not be able to create marker when floorfinding is not finished

### ISSUE THREAD

**Issue by bertt** [bertt/tango#37]
current behaviour: placing a marker immediatly after 'Start opname' gives a marker hanging in the air
expected behaviour: user should not be able to place markers when floor is not found (yet)

**Comment by bertt** [comment]
happens also with moving too quickly around in a area

**Comment by aiunderstand** [comment]
quick fix with events. Needs larger architecture refactor as performance get penalties due to implementation. Compare impl. to floorfindingexperiment example in tango repo. We want regular floor updates instead of on demand (eg. "just in time before marker is placed") since we analyse the floor further
